[functions.get-matches-v2]
enabled = true
verify_jwt = true
import_map = "./functions/get-matches-v2/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-matches-v2/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-matches-v2/*.html" ]

[functions.report-monthly-impression-usage]
verify_jwt = false
import_map = "./functions/import_map.json"

[db]
major_version = 15